# Generated by Django 5.2 on 2025-05-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='hobbies',
            new_name='Hobbies',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='job',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='Name',
        ),
    ]
