# Generated by Django 5.2 on 2025-06-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_age_info_age_rename_gender_info_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField()),
                ('Description', models.TextField()),
                ('Price', models.IntegerField(max_length=6)),
                ('Created_at', models.DateTimeField()),
            ],
        ),
    ]
