# Generated by Django 5.2 on 2025-06-01 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
