# Generated by Django 5.2 on 2025-06-13 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=75)),
                ('Image', models.ImageField(upload_to='static\\images')),
                ('Price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000000), django.core.validators.MinValueValidator(1000)])),
                ('Short_Description', models.TextField(max_length=300)),
                ('Material', models.CharField(max_length=100)),
                ('Place_of_Origin', models.CharField(max_length=100)),
                ('Width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Name', 'Image'), name='unique keyboard')],
            },
        ),
    ]
