# Generated by Django 5.2 on 2025-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_keyboard'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyboard',
            name='unique keyboard',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='Image',
        ),
        migrations.AddConstraint(
            model_name='keyboard',
            constraint=models.UniqueConstraint(fields=('Name',), name='unique keyboard'),
        ),
    ]
