# Generated by Django 5.2 on 2025-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_keyboard_unique_keyboard_keyboard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='Image',
            field=models.ImageField(default='bad_sign.png', upload_to='media'),
        ),
    ]
