# Generated by Django 5.2 on 2025-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_keyboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='Image',
            field=models.ImageField(default='bad_sign.png', upload_to='images'),
        ),
    ]
